### PR TITLE
Fix base64 string input - Closes #13

### LINKED ISSUE #13: parse base64 string correctly
**Expected behavior**

A base64 string should be parsed and handled correctly.

**Actual behavior**

A base64 breaks on parsing in Lisky

```
lisky> verify message 647aac1e2df8a5c870499d7ddc82236b1e10936977537a3844a6b05ea33f9ef6 --signature 'KjyhJ+/Peyv2KsjDsfWs9pl8q2K6n941Z9GI7cusvF3IF3+4jQOoaRzgM0j1abEhvKnno8Q79cBWOC81/4Q8CQ=' --message file:./message.txt
KjyhJ+/Peyv2KsjDsfWs9pl8q2K6n941Z9GI7cusvF3IF3+4jQOoaRzgM0j1abEhvKnno8Q79cBWOC81/"4Q8CQ=
```

### PR DESCRIPTION
**Pull request by toschdev**
Closes #13

### CODE REVIEW

File: test/integration.js [hunk 1]
```diff
@@ -357,6 +357,13 @@ describe('integration tests:', function () {
         });
       });
 
+      it.only('should parse base64 option', function (done) {
```
Comment (willclarktech) [inline test/integration.js]: `.only`

File: lib/vorpal.js [hunk 2]
```diff
@@ -97,7 +97,7 @@ function Vorpal() {
   });
 
   // Allow unix-like key value pair normalization to be turned off by toggling this switch on.
-  this.isCommandArgKeyPairNormalized = true;
+  this.isCommandArgKeyPairNormalized = false;
```
Comment (willclarktech) [inline lib/vorpal.js:100]: There's no way of altering this with an option passed when initializing a Vorpal instance?

File: test/integration.js [hunk 3]
```diff
@@ -357,6 +357,13 @@ describe('integration tests:', function () {
...
+        exec('say "KjyhJ+/Peyv2KsjDsfWs9pl8q2K6n941Z9GI7cusvF3IF3+4jQOoaRzgM0j1abEhvKnno8Q79cBWOC81/4Q8CQ=="', done, function () {
```
Comment (willclarktech) [inline test/integration.js]: Prefer storing the string in a variable so we can see it's the same.

**Review by willclarktech — DISMISSED** [review]

File: lib/vorpal.js (hunk 2 above)
Comment (toschdev) [reply lib/vorpal.js:100]: It does not seem to be intended. Even though we could add this, since we do not have the positive case planned (using unix-like key value pairs) - it does not seem to be necessary for this PR.
